### ISSUE TITLE
Set up a release strategy

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-font#1]
As discussed in https://github.com/simple-icons/simple-icons/pull/1307 we need to figure out a way to sync up releases of the [primary NPM package](https://www.npmjs.com/package/simple-icons) with the font version. I'm currently thinking of two different approaches: 1) publish an update for _simple-icons-font_ through the CI of _simple-icons_; and 2) build the font upon install.

Other suggestions and comments are welcome 😃 

## Publish through CI

This is the straightforward solution (in terms of how to approach this, implementing isn't that straightforward). We would need to find a way to extend the [`.travis.yml`](https://github.com/simple-icons/simple-icons/blob/develop/.travis.yml) configuration of the main repository to publish this (and potentially other packages) when an update for [the simple-icons package](https://www.npmjs.com/package/simple-icons) is published.

One way of doing this is through a bot/[GitHub Actions](https://github.com/features/actions) ([relevant comment](https://github.com/simple-icons/simple-icons/issues/982#issuecomment-475364447)).

Related issues to this are: https://github.com/simple-icons/simple-icons/issues/898, https://github.com/simple-icons/simple-icons/issues/770, and https://github.com/simple-icons/simple-icons/issues/982

## Build the font upon install

I'm not 100% sure how to achieve this, but I'm pretty sure it is possible to run a script when a dependency is installed with `npm install`. For example, I know [gulp-imagemin](https://www.npmjs.com/package/gulp-imagemin) runs some scripts when installing it as a dependency.

In this scenario we would add run [the build script](https://github.com/simple-icons/simple-icons-font/blob/ea13e87403a8539e74460d599f36f9f61bf8c711/package.json#L23) when the _simple-icons-font_ is installed as a dependency and have _simple-icons_ listed a dependency for _simple-icons-font_ such that it always uses the `@latest` version.

This significantly simplifies the release process for _simple-icons-font_. The main drawback is that it is an unconventional way to provide users with updates and it might be confusing for people using _simple-icons-font_ as a dependency. Basically, to update the package and get the latest icons one needs to `npm install simple-icons-font` again.

Another drawback is that I think this would make it so the package as provided by CDNs is never updated, so new icons won't become available there... 😞 

Again, I don't know how feasible this approach is. I will try to get something like this working as soon as possible and report my findings here 👍

**Comment by metaa** [comment]
I'd like to throw [this one](https://www.npmjs.com/package/lerna) in real quick.

**Comment by ericcornelissen** [comment]
Sorry for the delay. Below you'll find my initial findings ⬇️ 

Even though the "_Build the font upon install_" strategy is kinda nice and elegant, I think that because of the drawbacks publishing through the CI of the [main repository](https://github.com/simple-icons/simple-icons) is better. 🤔 

---

## Publish through CI

This can be _either_ through Travis CI in the [main repository](https://github.com/simple-icons/simple-icons) or with a bot/GitHub Actions(need to investigate this a bit more) that is triggered by a push there.

The best way of doing this, I think, would be to have an automated script that clones this repo, automatically updates the simple-icons dependency and version number and pushes the result back to this repo. The CI of this repo will then publish the change to NPM itself. This allows for separate changes 

One thing to consider here is how to update the version number. It seems straightforward to keep it in sync with simple-icons but then what do we do when this package needs a separate fix, wait for the next update of the simple-icons?

## Build the font upon install

From my testing (by installing the dependency from a git repository) this is possible. According to [the documentation for scripts](https://docs.npmjs.com/misc/scripts) only a `prepublish` script is required when installing from the NPM registry. But for my test with the git repository I had to add a `prepare` script that runs the build, when I added that the script the font was build locally and it worked perfectly.

## Lerna

(Thanks for the suggestion @metaa) from what I can tell [Lerna](https://www.npmjs.com/package/lerna) is supposed to be used with a mono-repo setup. The setup we're currently going for is a multi-repo setup.

Still it is important to remember this one if we can't figure things out 😄

**Comment by ericcornelissen** [comment]
While waiting for [this](https://github.com/simple-icons/simple-icons/issues/982#issuecomment-475364447) and while I figure out a good way to automate the release process, you're free to do (at least) a first release to NPM @metaa 

<sup>maybe first address #2</sup>

**Comment by metaa** [comment]
> you're free to do (at least) a first release to NPM @metaa

There we go: [![NPM Version](https://img.shields.io/npm/v/simple-icons-font.svg)](https://www.npmjs.com/package/simple-icons-font)

**Comment by ericcornelissen** [comment]
@metaa could you add me as a collaborator of the package on NPM? The correct username is "ericcornelissen".

**Comment by metaa** [comment]
> @metaa could you add me as a collaborator of the package on NPM? The correct username is "ericcornelissen".

Done. You don't show up as a collaborator yet, but I think that may be a thing that updates with the next version or something 🤔

**Comment by ericcornelissen** [comment]
If you're talking about this ⬇️ then indeed that will be updated if I publish an update. But you did add me as a collaborator 🙂 

![image](https://user-images.githubusercontent.com/3742559/59630029-2d902f00-913c-11e9-8072-8236762fad4c.png)

**Comment by ericcornelissen** [comment]
With  #18 any change pushed to `master` will be automatically released 🎉

**Comment by ericcornelissen** [comment]
Wondering if we can create a scheduled workflow that will try to merge `develop` into `master` automatically once a week if simple-icons has an update. If we align that with the schedule of the main project releases here should go out fully automatically (if we use a PAT for this workflow to ensure the commit on master triggers GitHub Actions). What do you think about that @mondeja?

**Comment by mondeja** [comment]
> If we align that with the schedule of the main project releases here should go out fully automatically (if we use a PAT for this workflow to ensure the commit on master triggers GitHub Actions).

Do you mean a webhook?

**Comment by mondeja** [comment]
I agree, but this would be unreliable if is not triggered several days in the week, in case the version has not been released on Sunday. I'm investigating if a repository can't receive a webhook from the main repo that could trigger the action, but I'm not sure...

**Comment by ericcornelissen** [comment]
Sounds nice, I was thinking if we can use [`workflow_dispatch`](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch) or [`repository_dispatch`](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch) after I shut down my computer. Turns out you already figured it our for me :smile: 

To make sure we're on the same page. The main repo would trigger a workflow in this repo after it released to NPM and than this repo will update the simple-icons dependency and bump its own version on `develop` and merge that into `master`.

I'm not quite sure which of `workflow_dispatch` and `repository_dispatch` makes more sense to use. Based on the documentation I feel like `workflow_dispatch` is more appropriate and potentially easier to use (seems like it is easier to access inputs) but if we want to follow the post you linked I'm totally fine with using `repository_dispatch` instead :+1:

**Comment by ericcornelissen** [comment]
Okay, I tried this out with some private repos and I think I got something that will work. First, considering that [the documentation](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch) says:

> You can manually trigger workflow runs. To trigger specific workflows in a repository, use the `workflow_dispatch` event. To trigger more than one workflow in a repository and create custom events and event types, use the `repository_dispatch` event. 

I went with the `workflow_dispatch` event since we really only want to trigger a single workflow. Then, we can use a Workflow looking something like the next one in the main repo:

```yml
name: Trigger workflow somewhere else
on:
  push:
    branches: [master]

jobs:
  trigger:
    runs-on: ubuntu-latest
    name: Trigger
    steps:
    - name: Dispatch remote workflow
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.SOME_PAT }}" \
          https://api.github.com/repos/simple-icons/simple-icons-font/actions/workflows/[WORKFLOW FILE]/dispatches \
          -d '{"ref":"master"}'
```

And a Workflow looking something like the next one in this repo:

```yml
name: Workflow triggered remotely
on: workflow_dispatch

jobs:
  respond:
    runs-on: ubuntu-latest
    name: Respond
    steps:
    - name: Respond
      run: echo "Do stuff"
```

I will try to set up a workflow in the main repository that triggers a workflow here in the coming days, once that is working we can start putting together the workflow in this repository to get it to do what we want it to do (i.e. automatically release a new version).

**Comment by ericcornelissen** [comment]
With https://github.com/simple-icons/simple-icons/pull/4533, lets wait for the next release and hope it triggers [an "Automated Releases" run](https://github.com/simple-icons/simple-icons-font/actions?query=workflow%3A%22Automated+Releases%22).

**Comment by ericcornelissen** [comment]
The v4.5.0 release (see https://github.com/simple-icons/simple-icons/commit/7a53ef36a75388819327aaa5d71f0cf889b67932) has [triggered](https://github.com/simple-icons/simple-icons/runs/1639371125) the [automatic releases workflow](https://github.com/simple-icons/simple-icons-font/actions/runs/459080676) of this repository. While we're catching up to v4.5.0 in this repo we can start working on [the workflow](https://github.com/simple-icons/simple-icons-font/blob/develop/.github/workflows/auto-release.yml) to automate the release process completely.

**Comment by ericcornelissen** [comment]
🎉 🎉 🎉 

v4.6.0 was released ([almost](https://github.com/simple-icons/simple-icons-font/pull/77#issuecomment-757492950)) [completely autoamtically](https://github.com/simple-icons/simple-icons-font/runs/1677049665?) to both [npm](https://www.npmjs.com/package/simple-icons-font/v/4.6.0) and [GitHub Releases](https://github.com/simple-icons/simple-icons-font/releases/tag/4.6.0).
