### ISSUE TITLE
TTF file positioning errors in flutter export

### ISSUE THREAD

**Issue by jlnrrg** [simple-icons/simple-icons-font#113]
### Kind of issue 

- [ ] Improvement
- [x] Bug
- [ ] Other, namely:

### Description

I provide the simple_icon library for [flutter](https://pub.dev/packages/simple_icons) and some of the users noticed that there seems to be a positioning error when it comes to the generated ttf file. (related [github issue](https://github.com/jlnrrg/simple_icons/issues/11))

Can you provide information regarding the build process of the ttf file and/or look into the positioning of eg. apple and play store icon?

**Comment by mondeja** [comment]
Hi @jlnrrg,

This error should be fixed in v6.1.0, which will be released in two days. When released, could you check that is working fine? I don't know how to reproduce the exact environment in which you've experienced it.

Cheers!

**Comment by jlnrrg** [comment]
@mondeja thanks for letting me know.
Just out of curiosity, what caused this?

As I have not experienced the error myself, this will be hard. But I will notify the users that noted the issue, for their feedback :+1: .

**Comment by mondeja** [comment]
> Just out of curiosity, what caused this?

I wrongly set the SVG font file parameters when created it, sorry should have further debugged the glyph measurements. Has been fixed by #145.

**Comment by mondeja** [comment]
I'm closing this, reopen it if you receive more feedback about it.

**Comment by jlnrrg** [comment]
@mondeja I received feedback on my side and was able to reproduce the issue.
It seems that using a service like [icomoon](https://icomoon.io/) produces a centered version of the icons.
With the latest SimpleIcons.ttf file (and apparently every other) there are certain misalignments which you can see in this [response](https://github.com/jlnrrg/simple_icons/issues/11#issuecomment-1030836625).

If you could check on your side (/or with other package maintainers) if this is also a visible "problem" on their side, so we can narrow down the issue, this would be awesome :sweat_smile:.

**Comment by mondeja** [comment]
Hi, with the release of the latest v7.4.0 we've changed some settings in the font building that could have affected to this problem. Would you mind to try with that? Thanks
