### ISSUE TITLE
Reduce the number of available ligatures to 1 per icon

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-font#13]
Currently the font supports three ligatures (for most) icons, limiting this to just one can reduce the size of the output font. It's not much, as the table below shows, but it only becomes more beneficial over time. Also, I don't really see a reason to support three input values for the same icon, especially with #6 in mind.

| File | Size before (in bytes) | Size after (in bytes) |
|---|---|---|
| `SimpleIcons.woff` | `222,084` | `216,236` |
| `SimpleIcons.woff2` | `192,436` | `188,184` |

**Comment by mondeja** [comment]
I agree, more than one name also can confuse users. Could you finish the #6 review or close it to be able to continue with the issues @ericcornelissen?

**Comment by mondeja** [comment]
I would go for this now.

- We choose the slug, title or lowercase title?
- Also, the replace `.replace(/[ !’]/g, '')` is still valid? So we take the opportunity to update the version of simple-icons.

**Comment by ericcornelissen** [comment]
> 
> 
> I would go for this now. The problem is the mix of different letters between icons. For example, the icon `CircleCI` is rendered with two icons `Circle` `C`. Or `curl` is rendered with `C` `R`. You can test this opening the WOFF file with https://opentype.js.org/
> 
> I suppose that this is a misunderstanding of how works WOFF. Maybe each unicode character must render a glyph?
> 
> EDIT: Reported in #30 👀

You're right @mondeja, this is the exact problem I described in #30. I'm not super familiar with font types so it could be a misunderstand of how WOFF works. As I said in #30, if the current approach doesn't work rendering it using a unique Unicode character is probably the best way to go (_the "standard font file approach"_).
