### ISSUE TITLE
Changing size

### ISSUE THREAD

**Issue by 0lelouch** [simple-icons/simple-icons-font#157]
### Kind of issue 

- [x ] Improvement
- [ ] Bug
- [ ] Other, namely:

### Description
Can we change the size in [simple-icons-font](https://github.com/simple-icons/simple-icons-font#jsdeliver)? In [materialdesignicons](https://materialdesignicons.com/) I can do
```<i class="mdi mdi-facebook mdi-48px" aria-hidden="true"></i>```
`si-48px` is not working.

**Comment by sachinraja** [comment]
You can change the `font-size`.

Example:
```html
<i class="si si-facebook" style="font-size:48px" aria-hidden="true"></i>
```

**Comment by 0lelouch** [comment]
Thanks again

<img src="https://media2.giphy.com/media/zKBcZUw49Sxtm/giphy.gif"/>
