### ISSUE TITLE
Font assets not included in PHP package

### ISSUE THREAD

**Issue by bobmagicii** [simple-icons/simple-icons-font#186]
is the composer package meant to include pre-compiled css and font files? the instructions here were pretty spartan and suggestive as such. it would be pretty great if so. or are we meant to go in there and deal with npm related stuff too? asking for a friend who is not a fan of front end and who is also me.

![image](https://user-images.githubusercontent.com/881944/221723956-93b3a545-ed73-471b-bfcf-069f3b8aa209.png)

**Comment by bobmagicii** [comment]
why have the composer package then? *shrug*

**Comment by mondeja** [comment]
Sorry I haven't understood what you was trying to said.

This is true, the `dist` folder is not generated before we "upload" to Packagist. I'm not sure how can we upload these assets to Packagist as they just release the tag pushed to Github. This problem can be checked downloading manually the latest version through [this URL](https://api.github.com/repos/simple-icons/simple-icons-font/zipball/523bb329fee2e2e2a191a9f136a07b11bb899a82).

Unfornunately I don't have time to work on this nor motivation as I don't have used PHP in my whole life. This integration was added by a developer that is no longer part of the Simple Icons maintainer team. If someone want to bring a solution feel free to open a PR.

**Comment by bobmagicii** [comment]
alright, i'll hit up my composer buddies for suggestions before i submit an idea with a sledgehammer that could have been a screwdriver.

**Comment by bobmagicii** [comment]
after discussing with some peeps about what we're used to seeing in our corner of the eco system i got back three main ideas. none of these are demands just what i got back in my polling.

1) my least fav - just not have the package. right now its a very goofy series of events where you would `composer install` and then download the release.zip. when you could just... download the release.zip. right now its got 37 downloads according to packagist.org, and at least 4 of them are me, so i don't forsee a swamping of issue tickets of people being like "what the hell" the rest of your life heheh.

2) amend the readme with more verbose how to for the less js front end toolchain inclined like us backenders. how do we go from `cd vendor/simple-icons/simple-icons-font` to having a working css and font file in there, etc.

3) my personal fav because it seems more common in my experience: change build practices such that you compile a dist dir, commit it, tag it, and you are done. no more ever uploading a release.zip, people just download the zip github will make and associate with that tag automatically. then the manual installers and the backend installers have everything they need. obviously i am not equipped to judge how this would mess with the npm normies.

**Comment by mondeja** [comment]
The solution is much more simpler but I don't have the motivation to do it testing it manually.

Just add a step to the publish workflow ([after this step](https://github.com/simple-icons/simple-icons-font/blob/db7ab529fcec152843c5f3f1065f76f683774a7f/.github/workflows/publish.yml#L64)) to build the fonts before tagging the release, including the generated distribution folder (*dist/*) on the tag. After that, the fonts will be included in the Packagist package.
