### ISSUE TITLE
Font does not work in Firefox

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-font#19]
As per https://github.com/simple-icons/simple-icons-font/issues/14#issuecomment-514057250 it appears that the font ligatures are not being displayed at all in Firefox `68.0` (64-bit).

**Comment by metaa** [comment]
Are you viewing the test page as a local file on your PC?

I guess you are having [this "problem"](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp). Your Firefox isn't allowed to load local font files without explicit allowance (like command line flags (at least that's what you can do with Chrome) or settings).

If you open it served from a web server¹, it will display correctly:

![image](https://user-images.githubusercontent.com/5056880/61707057-e94f0a80-ad49-11e9-9f77-a2749dae4272.png)

¹ I like to use [anywhere](https://www.npmjs.com/package/anywhere). Go to your directory and run `npx anywhere`.

**Comment by ericcornelissen** [comment]
> Are you viewing the test page as a local file on your PC?

That is indeed the case.


> If you open it served from a web server¹, it will display correctly:

Okay, I will try that as soon as possible and report back here.

If this is indeed the case we should consider making it easy for contributors to do run such a server locally (perhaps using _anywhere_) so they can easily test it in Firefox (and Chrome if they changed the setting) if they so choose. Making their life's easier and preventing anyone from reporting this "bug" in the future.

**Comment by ericcornelissen** [comment]
> Okay, I will try that as soon as possible and report back here.

Works perfectly 😄 Very interesting, wasn't aware this was a thing.


> If this is indeed the case we should consider making it easy for contributors to do run such a server locally (perhaps using anywhere) so they can easily test it in Firefox (and Chrome if they changed the setting) if they so choose. Making their life's easier and preventing anyone from reporting this "bug" in the future.

I made this anyway while I was trying to see if the suggestion fixed the bug, so I opened #23
