### ISSUE TITLE
Allow usage of the font on any HTML element

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-font#2]
Is it really necessary to use an `<i>` tag when you want to use a simple-icon (see ⬇️)?

I know [FontAwesome](https://fontawesome.com/) "recommends" it (and maybe others as well), but I would say pretty much any element that is given the class `.simpleicons` should be converted into a simple-icon.

https://github.com/simple-icons/simple-icons-font/blob/6f4ef79a3445a5ce9742dac87900b19a3ac1d39a/font/font.css#L7

**Comment by metaa** [comment]
Yeah, you're right, serving a class named `simpleicons` is verbose enough and I was in fact biased by other icon collections using the `i` tag.

If someone decides to put it on some other tag (like `input`?), or they're using shiny new custom HTML tags, then so be it, they can use whatever they want.

We should change that selector.
