### ISSUE TITLE
Font building fails for new icons in Simple Icons

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-font#29]
As one can see [in the Travis CI build](https://travis-ci.com/simple-icons/simple-icons-font/builds/138269917#L1058) there is an issue with new SVG that are being added the Simple Icons for the font building pipeline we use.

I'm not sure about the exact details of the issue, whether it is a problem with the SVGs or with our tooling. On the one hand many of the SVGs causing trouble also don't load properly in my editing software. On the other hand these SVGs are all compressed using [SVGO](https://github.com/svg/svgo) or [SVGOMG](https://jakearchibald.github.io/svgomg/)...

I worked around this problem earlier [by patching the icons that were a problem for this project](https://github.com/simple-icons/simple-icons/pull/1718) but that is a bit much work (though I think we would accept pull request for it over in the main repository if anyone wants to do it...).

A solution would be help in order to keep this project up-to-date with the main project. Either fix the pipeline we use or make sure the SVGs added in the main project are compatible with the tooling here.

**Comment by mondeja** [comment]
I've been doing some research on this problem and it seems that sax (dependency on svgicons2svgfont, which is dependency on icon-font-buildr) is not able to parse certain SVG paths, but the project is not maintained, as is svgicons2svgfont.

**Comment by ericcornelissen** [comment]
I'd be completely okay with switching the dependencies to something that does work, if you are able to find something @mondeja
