### ISSUE TITLE
Overlapping names confuses ligatures and wrong icons are displayed

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-font#30]
Have a look at the image below, you might see the logo for the C and R programming languages quite often 😕 

This is because the ligature for e.g. "CoronaRenderer" (highligted in the image) contains a C and 4 R's and instead of showing the ligature for it shows 1 for the C programming language and 4 for the R programming language.

I'm not sure if fonts can be somehow tweaked to look for the longest ligatures first... One interesting observation is that the different browsers show different icons differently. For example the Corona Renderer logo doesn't show in Firefox (below) but works in Chrome.

![image](https://user-images.githubusercontent.com/3742559/73123678-f5d34a80-3f9a-11ea-9d9d-2dae507c146c.png)

**Comment by metaa** [comment]
I feel like we've had that somewhere in a previous issue or that I already resolved it but I don't quite know where right now 🤔 

I'll test and see what I can find.

**Comment by metaa** [comment]
Interestingly I only get two cases in both Chrome (1) and Firefox (2).
![image](https://user-images.githubusercontent.com/5056880/73127712-e2d57000-3fc4-11ea-8476-d5eb154ee750.png)

![image](https://user-images.githubusercontent.com/5056880/73127725-1fa16700-3fc5-11ea-916b-d234df8140ce.png)

**Comment by ericcornelissen** [comment]
Well, [Elsevier](https://github.com/simple-icons/simple-icons-font/blob/6749be9867d054ce1be3869617bdbb6c5db8157c/scripts/build.js#L12) is not part of the font so that makes sense (should probably update [testpage.pug](https://github.com/simple-icons/simple-icons-font/blob/6749be9867d054ce1be3869617bdbb6c5db8157c/preview/html/testpage.pug) accordingly). Also, there seems to be an extra instance of the "C" programming language right to the icon for CodeCoverage (which, surprisingly, does work correctly for me 🤣)

I don't recall this being discussed before and I had never noticed it myself. It is very weird that there is such a discrepancy between our results... Perhaps this is a reason why other projects don't use ligatures for this kind of stuff? 🤔 Unless this can somehow be configured in the font file, I am afraid we will need to resort to the "standard font file approach"...
