### ISSUE TITLE
How to use font?

### ISSUE THREAD

**Issue by OldShaterhan** [simple-icons/simple-icons-font#36]
Hey guys,
I'm not sure how to use font. I installed it within Angular project and I want to use now it. I assume I did proper importing to the main SCSS file.
Could you provide an example how to use it?

Thanks in advance.

**Comment by metaa** [comment]
Oh, I forgot we didn't have an example yet.
I will set something up this weekend.

I don't know the specifics about Angular, but since you're using SCSS I don't think it's gonna be anything special.

**Comment by OldShaterhan** [comment]
Thanks. Any update? I believe classic example would be okay ;)

**Comment by ericcornelissen** [comment]
Thank you for the request @OldShaterhan, I'm closing this in favor of #5. We plan on continuing the development of this font, and hope proper documentation will be available in the future.
