### ISSUE TITLE
Increase functionality of test page

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-font#41]
Would be interesting to have a toggle, besides light/dark background, on the test page that switches between:

- [ ] The class variant and the ligature variant
- [x] Black icons and brand colored icons - #43

**Comment by mondeja** [comment]
> The class variant and the ligature variant

This is superseded by #45? I'm not sure :thinking:

**Comment by ericcornelissen** [comment]
It does @mondeja
