### ISSUE TITLE
Consideration: shorter class names

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-font#57]
I'm wondering whether we should use shorter class names, this has several obvious advantages and apart from backwards compatibility no real downsides - luckily we still have two major release for breaking changes at this point (the releases corresponding to simple-icons v3 and v4).

Following [Font Awesome](https://fontawesome.com/)'s `fa` class and `fa-` prefixed classes I suggest we go with the `si` class and `si-` prefixed classes. The only thing I'm unsure about is the _"color modifier"_ class (currently `simpleicons--color`), I'm not sure if `si--color` works so well but I would be happy with it if there are no other suggestions as I prefer `si` over `simpleicons` as a prefix.

Thoughts?

\cc @mondeja

**Comment by mondeja** [comment]
Yes, I completely agree 👍
