### ISSUE TITLE
Specify minimum NodeJS version requirement to package.json

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-font#67]
Following https://github.com/simple-icons/simple-icons/pull/3979, I think we should specify a minimum NodeJS version in this project's [package.json](https://github.com/simple-icons/simple-icons-font/blob/3f2b6eab6e1fabb1866d003e989137bd0e104d9c/package.json).

**Comment by mondeja** [comment]
:thinking: Since the package distribution of this project doesn't uses Javascript at all, maybe is not even necessary.

**Comment by ericcornelissen** [comment]
Fair point, in that case I will close this for now.
