### ISSUE TITLE
Github event support

### ISSUE THREAD

**Issue by jlnrrg** [simple-icons/simple-icons-font#97]
I published a wrapper for the simple icons in the flutter community, [pub.dev](https://pub.dev/packages/simple_icons).
The library works by running `npm install simple-icons-font` and converting the SimpleIcons.ttf into a dart class.

To have a fully automated build, it would be create, if we could work out a synergy, where this repo provides an event my github action can listen to, every time a new version is released (to npm).

**Comment by ericcornelissen** [comment]
My initial response would be to use either [RenovateBot](https://www.whitesourcesoftware.com/free-developer-tools/renovate) or [dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) to keep the simple-icons-font dependency up-to-date (both can be configured with automatic merging). Alternatively, we have a fairly regular release schedule on which you can base your automation. But I have no idea if any of this works for your setup - could you provide more details on that?

We _could_ set up something similar to [what we use internally already for the font and (new) website](https://github.com/simple-icons/simple-icons/blob/ac633dc120e4aa28d181f6d02bda2e417110b0be/.github/workflows/publish.yml#L72-L93), but as your repository is external I would be inclined to shy away from that.

**Comment by jlnrrg** [comment]
I personally have no experience with either RenovateBot or dependabot.
My initial search lead me to [repository-dispatch](https://github.com/peter-evans/repository-dispatch) in this [stackoverflow](https://stackoverflow.com/questions/58465057/trigger-a-github-action-when-another-repository-creates-a-new-release) thread.

As far as I understood it, this might also be beneficial for other packages that like to listen to the dispatch. Also the repositories would not touch, if that was your issue.

**Comment by ericcornelissen** [comment]
> I personally have no experience with either RenovateBot or dependabot.

You should definitely check them out if you have time :smile: Though unfortunately it seems the Flutter/Dart ecosystem isn't supported by either of these services... So it doesn't seem like we can use it here :disappointed: Though you said you get the font from NPM, correct?

> My initial search lead me to [repository-dispatch](https://github.com/peter-evans/repository-dispatch) in this [stackoverflow](https://stackoverflow.com/questions/58465057/trigger-a-github-action-when-another-repository-creates-a-new-release) thread.
> 
> As far as I understood it, this might also be beneficial for other packages that like to listen to the dispatch. Also the repositories would not touch, if that was your issue.

I believe this is more or less what I said in the second paragraph ("We _could_ [...]"). The main drawback is that, if I'm not mistaken, this doesn't work by other repositories "listining in" (subscribing would be the proper term I think) but instead requires us to list repositories to dispatch to. Again, this is possible but I would like to avoid it with external projects.

Again, if you could try and explain how your current automation works I have a better picture of the situation and will be able to better support you :smiley:

**Comment by jlnrrg** [comment]
Ok, I thought it would work by subscribing. I'll look into that. 
If it really needs to push to each new repository it is not a solution I would like to bother you with.
Now that I think about it, the dependabot might be right.

The main automation happens in the [build.sh](https://github.com/jlnrrg/simple_icons/blob/master/tool/build.sh):
1. `npm install --force simple-icons-font`
2. copy the ttf font to another location
3. call [ttx of fonttools](https://github.com/fonttools/fonttools) to get the fonts xml
4. map the xml to dart code

**Comment by mondeja** [comment]
You could solve this by:

1. Create a Github Action workflow executed on Monday and Tuesday (simple-icons packages are released on Sundays, Monday at the latest if a release is delayed for any reason),
2. In your `pubspec.yaml` keep synchronized the version of `simple-icons-font` (the same as `simple-icons`)  with the version of your package. So, at the execution of the workflow, you only need to check if the version of the `simple-icons-font` package has changed comparing it against the version defined in your `pubspec.yaml`. You can use NPM directly to get the latest version: `npm show simple-icons-font version`

**Comment by jlnrrg** [comment]
@mondeja thanks for your participation.
1. that might be the best low effort implementation, thanks for the hint
2. The whole reason is that I search for a good trigger to start the workflow (I think you'd assume here to start it scheduled, too)

@ericcornelissen I decided to implement dependabot.
Therefore I created a [node directory](https://github.com/jlnrrg/simple_icons/tree/master/node), where the bot watches the package.json

**Comment by ericcornelissen** [comment]
> The "subscriber strategy" only has sense if you need the publication of the package at the same time of simple-icons for some reason, but I don't think that this would be needed for in this case.

I think that if it is possible to do a subscriber-based strategy, this is something we should (or at least could) support - if only because I think we should be using it internally over what we are [doing now](https://github.com/simple-icons/simple-icons/blob/ac633dc120e4aa28d181f6d02bda2e417110b0be/.github/workflows/publish.yml#L72-L93). However, as [this example](https://github.com/peter-evans/repository-dispatch#dispatch-to-multiple-repositories) demonstrates, `repository-dispatch` is not subscriber-based.


> I think you'd assume here to start it scheduled, too

That is correct


> I decided to implement dependabot.
> Therefore I created a node directory, where the bot watches the package.json

Cool! Let us know here how that works out for you :smile: Just a precautionary question: dependabot, I believe, will only update the `package.json` and `package-lock.json` file, is the rest of your project still prepared to update the contents of the `node_modules/` directory?

I've got two suggestions for you on this approach: 

- You should be able to reliably ignore anything we add to the package in your repository by putting a `.gitignore` in your `node/` directory similar to

  ```gitignore
  # ignore everything in node_modules
  node_modules/
  # except for the font files of simple-icons-font
  !node_modules/simple-icons-font/font
  # or be more precise and only allow the font file(s) you're interested in. (in which case you need to omit the previous line)
  !node_modules/simple-icons-font/font/SimpleIcons.ttf
  ```
- I'm not sure what the conventions are in Flutter/Dart, but to the best of my knowledge the folder you currently call `node` is typically called `vender`. If you still want to make clear that this is a node thing, you can still put it in `vender/node`

Again, these are just suggestions. The first should reduce your repository size over time (as fewer diffs have t be recorded) while the second should help outsiders understand the structure of your project.

**Comment by jlnrrg** [comment]
Your feedback is very much appreciated and I implemented as you've said.
Regarding dependabot, I'll wait for the first pull request to be triggered and then intend to redesign my build method action to listen to these specific PRs

**Comment by jlnrrg** [comment]
@ericcornelissen even though I aim everything to be automated it would be great if one or two of your team would volunteer to gain access to my repository, just to be safe nothing happens like in the previous package.

**Comment by ericcornelissen** [comment]
Given that 1) none of us have sufficient experience with Flutter or Dart (correct me if I'm wrong) and 2) we already have our hands full, I think we should hold off on that for now. Ultimately, third parties are responsible for maintaining [third-party packages](https://github.com/simple-icons/simple-icons#third-party-extensions), if they go stale that is too bad. If simple-icons as an organisation wants to support Flutter/Dart with a first-party extensions in the future, we can contact you - and in the case that you don't respond we can still use your project as a jumping off point, it is open source after all :wink: 

With that I'll close this for now, just to keep the list of open issues in this repository as short as possible. You can still use this thread if you want to talk to us about your package @jlnrrg (and do let us know if you need help with your automation!)

**Comment by jlnrrg** [comment]
@ericcornelissen do you keep a changelog file stored somewhere?

background:
I am in the process of equaling my package verison based on this repo and would like to include real change messages.
In flutter it is necessary to have a [changelog.md](https://github.com/jlnrrg/simple_icons/blob/master/CHANGELOG.md), where the version of [pubspec.yaml](https://github.com/jlnrrg/simple_icons/blob/master/pubspec.yaml) (which is like package.json) has to have an entry there.

**Comment by ericcornelissen** [comment]
Unfortunately for this situation, we don't, neither in this font repository nor in [the main repository](https://github.com/simple-icons/simple-icons/tree/da8206aca16c16bc54b901ff598251d1bb7fbb45). The closest things we have are the descriptions of [the GitHub releases in the main project](https://github.com/simple-icons/simple-icons/releases) and the Pull Request descriptions of [`release` Pull Requests in the main project](https://github.com/simple-icons/simple-icons/pulls?q=is%3Apr+is%3Aclosed+label%3Arelease). I understand that this may be a bit difficult to deal with for you...

**Comment by ericcornelissen** [comment]
I would personally not be against including a `CHANGELOG.md` in the main project (having a duplicate here for occasional changes to the font seems pointless to me) given that it is generated/updated automatically. However, other @simple-icons/maintainers would need to agree with that decision.

**Comment by jlnrrg** [comment]
That already helped me a lot. I was not aware your release notes are so comprehensive.
Thus i can run `curl -sL https://api.github.com/repos/simple-icons/simple-icons/releases | jq -r '.[] | select(.tag_name == "4.10.0") | .body'` and get the body easily.

@ericcornelissen do you know a tool by any chance to modify markdown?
For example your release body has h1 header, but in my changelog they must not be h1. Of cause I can just replace all # with ##, but maybe there is a hidden tool I am not aware of.

**Comment by ericcornelissen** [comment]
> That already helped me a lot. I was not aware your release notes are so comprehensive.
Thus i can run curl -sL https://api.github.com/repos/simple-icons/simple-icons/releases | jq -r '.[] | select(.tag_name == "4.10.0") | .body' and get the body easily.

My CLI skills are not that advanced, but to me that looks like something that should work :slightly_smiling_face: As an aside, it may be simple if you use the URL `https://api.github.com/repos/simple-icons/simple-icons/releases/tag/4.10.0` (where `4.10.0` can be replaced by the version you're interested in) instead.


> do you know a tool by any chance to modify markdown?
> For example your release body has h1 header, but in my changelog they must not be h1. Of cause I can just replace all # with ##, but maybe there is a hidden tool I am not aware of.

Not that I'm aware of, probably your best bet is to replace `#` by `##`.

**Comment by jlnrrg** [comment]
great idea. But for future reader the link is `https://api.github.com/repos/simple-icons/simple-icons/releases/tags/4.10.0`

Thus the whole command
curl -sL https://api.github.com/repos/simple-icons/simple-icons/releases/tags/4.10.0 | jq -r '.body'

**Comment by jlnrrg** [comment]
As this took quite some time to achieve (I am not an bash expert myself),
here the solution to read the simple-icons release body and format for external packages:

 ```bash


    # get release body
    CHANGELOG=$(curl -sL https://api.github.com/repos/simple-icons/simple-icons/releases/tags/$VERSIONNUMBER | jq -r '.body')

    # replace single # with ###
    CHANGELOGHEADERMOD=$(echo "$CHANGELOG" | sed -e "s/^#/###/g")

    # replace github issue number with real link
    CHANGELOGMOD=$(echo "$CHANGELOGHEADERMOD" | sed -E "s/(\()(#)([0-9]*)(\))/[(#\3)](https:\/\/github.com\/simple-icons\/simple-icons\/pull\/\3)/g")
```

**Comment by jlnrrg** [comment]
@ericcornelissen was there a change I am not aware of?
The release body I get from the github api is empty for verison [4.12.0](https://api.github.com/repos/simple-icons/simple-icons/releases/tags/4.12.0) even though it has a body in [releases](https://github.com/simple-icons/simple-icons/releases).

**Comment by ericcornelissen** [comment]
@jlnrrg, unfortunately https://github.com/actions/create-release is no longer being maintained so the issue won't be fixed there. It does not seem there are particularly viable alternatives, and given that `actions/create-release` still works fine for our purposes I'm hesitant to change anything about the release strategy as it is now...

**Comment by jlnrrg** [comment]
@ericcornelissen  
Do you push the changes at a specific time?
Then I could specify my dependabot on one hour before that, giving you 23h time to fill in the body.

**Comment by ericcornelissen** [comment]
Again, to get the body as you're currently using it, we need to go into the GitHub releases, manually write (or copy & edit from the release Pull Request) the release body and update the release. While it is not a lot of work, from our perspective it is not that hard to forget and some extra work that is not worth the really worth the effort (remember, we're just a group of volunteers working on this in our free time).

I'd really recommend you to reconsider your approach here and just link to our release notes instead. As I see it the has the advantage that 1) it requires no extra work from our side, 2) your script becomes simpler, 3) your script doesn't need to be changed if we decide to change the structure of our release notes, and 4) the release notes are updated if they contain a mistake. The only "downside" being that your users need to click on a link when they want to see the release notes. If you disagree, please tell us why it is important for you to have a copy of what is already available online in your project.

**Comment by jlnrrg** [comment]
Thank is a great recommendation. I just couldn't see the wood for the trees. :smile:
